name: VelocityCheckin

on:
  push:
    branches:
      - main
  
env:
  sourceEnvironment: prod
  sourceBranch: main
  sourceRevision: ${{ github.sha }}
  sourceRepo: ${{ github.server_url }}/${{ github.repository }}
  sourceVersion: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
  secrets:
    VELOCITY_DEPLOYMENT_TOKEN: ${{ secrets.VELOCITY_DEPLOYMENT_TOKEN }} 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -d "token=${{ secrets.VELOCITY_DEPLOYMENT_TOKEN }}" -d "revision=${{ env.sourceRevision }}" -d "repository_url=${{ env.sourceRepo }}" -d "branch=${{ env.sourceBranch }}" -d "version=${{ env.sourceVersion }}" -d "environment=${{ env.sourceEnvironment }}"  https://velocity.codeclimate.com/deploys
